# Generated by Django 5.2.5 on 2025-10-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
