# Generated by Django 5.2.5 on 2025-10-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_token_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecounter',
            name='current_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_at', to='queue_app.token'),
        ),
        migrations.AddField(
            model_name='token',
            name='completed_serving',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='started_serving',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
