# Generated by Django 5.2.5 on 2025-10-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_servicecounter_current_token_token_completed_serving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecounter',
            name='last_token_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
